"""AnalysisReport ORM model – monthly feature analysis results.

Stores structured analysis results (correlations, feature importance,
hypothesis test results) and an HTML report for each monthly run.
Generated by the automated feature analysis pipeline (Sprint 9).
"""

from datetime import date, datetime

from sqlalchemy import (
    Date,
    DateTime,
    Float,
    Index,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from trading_signals.db.base import Base


class AnalysisReport(Base):
    """Monthly feature analysis report.

    Stores the full results of Spearman correlations, Random Forest
    and LASSO feature importance, hypothesis tests, and consensus
    feature rankings. The HTML report with embedded plots is stored
    for direct serving via the API.
    """

    __tablename__ = "analysis_reports"
    __table_args__ = (
        Index("idx_analysis_reports_date", "report_date"),
        {"schema": "signals"},
    )

    # ── Primary Key ──────────────────────────────────────────────────
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # ── Report Metadata ──────────────────────────────────────────────
    report_date: Mapped[date] = mapped_column(Date, unique=True, nullable=False)
    snapshot_count: Mapped[int] = mapped_column(Integer, nullable=False)
    ticker_count: Mapped[int] = mapped_column(Integer, nullable=False)
    date_range_start: Mapped[date] = mapped_column(Date, nullable=False)
    date_range_end: Mapped[date] = mapped_column(Date, nullable=False)

    # ── Structured Results (JSONB) ───────────────────────────────────
    # Spearman correlations: {feature: {return_1d: {rho, pvalue}, ...}}
    feature_correlations: Mapped[dict | None] = mapped_column(JSONB)

    # Random Forest permutation importance: {feature: {importance, std}}
    feature_importance_rf: Mapped[dict | None] = mapped_column(JSONB)

    # LASSO coefficients: {feature: coefficient}
    feature_importance_lasso: Mapped[dict | None] = mapped_column(JSONB)

    # Hypothesis results: {H1: {verdict, pvalue, effect_size, detail}, ...}
    hypothesis_results: Mapped[dict | None] = mapped_column(JSONB)

    # Top features consensus: [{feature, spearman_rank, rf_rank, lasso_rank}, ...]
    consensus_features: Mapped[list | None] = mapped_column(JSONB)

    # ── HTML Report ──────────────────────────────────────────────────
    html_report: Mapped[str | None] = mapped_column(Text)

    # ── Performance Metadata ─────────────────────────────────────────
    computation_time_seconds: Mapped[float | None] = mapped_column(Float)
    computed_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now()
    )

    def __repr__(self) -> str:
        return (
            f"<AnalysisReport(date={self.report_date}, "
            f"snapshots={self.snapshot_count}, "
            f"tickers={self.ticker_count})>"
        )
